services:
  client:
    build: client
    ports:
      - "3500:3500"
    env_file:
      - client/.env
    depends_on:
      - server

  server:
    build: server
    ports:
      - "4500:4500"
    environment:
      - NODE_ENV=production
    env_file:
      - server/.env
    depends_on:
      - pg

  pg:
    image: postgres:15
    container_name: postgres
    ports:
      - "5431:5432"
    env_file:
      - server/.env
    volumes:
      - /home/ubuntu/eee-inv-pg-data:/var/lib/postgresql/data

volumes:
  pgdata:
