name: Redeploy V1-Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Pull main and deploy newest code for V1-Testing
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          cd /home/ubuntu/eee-inventory
          git pull
          docker compose up --build -d
