name: Redeploy V1-Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Pull main and host the newest code for V1-Testing
    runs-on: self-hosted
    steps:
      - name: clone repo and update
        run: |
          cd /home/ubuntu/eee-inventory
          git pull
          docker compose up --build -d